#!/usr/bin/env bash
# lock-quote by Amory Meltzer
# Stochastically change the lock screen quote in OSX from a quotes file

quotefile=lockscreen_quotes.txt

jo=$(shuf < $quotefile | head -n 1)

echo "$jo"
