#!/usr/bin/env bash
# lock-quote by Amory Meltzer
# Stochastically change the login/lock screen quote in OSX using a quotes file

function help {
    cat <<END_HELP
Usage: $(basename "$0") [-fsnhH]

  -f		Provide a path to a file of quotes, one per line.  Overrides LOCK_SCREEN_QUOTES.
  -s		Show the current text used on the login/lock screen.  No sudo required.  Overrides -n.
  -n		Show a quote but don't use it.  No sudo required.
  -h -H		This help.
END_HELP
}

# Set the quotes file
# Default to using environment variable
if [[ -n "$LOCK_SCREEN_QUOTES" ]]; then
    quotefile="$LOCK_SCREEN_QUOTES"
fi

while getopts 'f:snhH' opt; do
    case $opt in
	f) quotefile=$OPTARG;;
	s) defaults read /Library/Preferences/com.apple.loginwindow.plist LoginwindowText
	   exit 0;;
	n) dryrun=1;;
	h|H) help
	     exit 0;;
	*) printf "Invalid option provided, try %s -h\n" "$0" >&2
	    exit 1;;
    esac
done

if [[ ! -e "$quotefile" ]]; then
    # Get this script's directory: http://stackoverflow.com/a/246128/2521092
    DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    quotefile=$DIR/lockscreen_quotes.txt
fi


# OSX doesn't have shuf, approximate it via perl
# https://stackoverflow.com/a/6511327/2521092
if [[ ! $(command -v 2>/dev/null shuf) ]]; then
    function shuf() {
	perl -MList::Util=shuffle -e 'print shuffle(<>);' "$@";
    }
fi
qo=$(shuf "$quotefile" | head -n 1 | tr -d '\n')
qo=$(echo "$qo" | sed -Ee 's/\[|\]//g' | sed -e "s/\"//g" | sed -e 's/ - / \]- /' | tr ']' '\n')

if [[ -n "$dryrun" ]]; then
    echo "$qo"
    exit 0
fi

defaults write /Library/Preferences/com.apple.loginwindow.plist LoginwindowText "$qo"
